package junit.com.svenruppert.urlshortener.client;

import com.svenruppert.dependencies.core.logger.HasLogger;
import com.svenruppert.urlshortener.api.ShortenerServer;
import com.svenruppert.urlshortener.client.URLShortenerClient;
import com.svenruppert.urlshortener.core.urlmapping.BulkShortenResponse;
import com.svenruppert.urlshortener.core.urlmapping.BulkShortenResponse.BulkShortenItemResult;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.net.Socket;
import java.time.Duration;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;

import static com.svenruppert.urlshortener.core.DefaultValues.ADMIN_SERVER_HOST;
import static com.svenruppert.urlshortener.core.DefaultValues.DEFAULT_SERVER_HOST;
import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration tests for {@link URLShortenerClient#bulkShorten(List)}.
 *
 * <p>Each test starts a fresh embedded {@link ShortenerServer} on dynamic ports and
 * connects a {@link URLShortenerClient} to it, mirroring the pattern used throughout
 * the client test suite.
 */
class URLShortenerClient_BulkShortenTest implements HasLogger {

  private static final String URL_A = "https://example.com/page-a";
  private static final String URL_B = "https://example.org/page-b";
  private static final String URL_C = "https://openai.com/docs";
  private static final String INVALID_URL_NO_SCHEME = "not-a-url-at-all";
  private static final String INVALID_URL_BAD_SCHEME = "ftp://forbidden.example.com";
  private static final String INVALID_URL_NO_TLD = "http://localhost";

  private ShortenerServer server;
  private URLShortenerClient client;

  // ─── Lifecycle ────────────────────────────────────────────────────────────

  @BeforeEach
  void startServer() throws Exception {
    server = new ShortenerServer();
    server.init(DEFAULT_SERVER_HOST, 0);
    waitUntilOpen(DEFAULT_SERVER_HOST, server.getPortRedirect(), Duration.ofSeconds(3));

    final String adminUrl    = "http://" + ADMIN_SERVER_HOST + ":" + server.getPortAdmin()    + "/";
    final String redirectUrl = "http://" + DEFAULT_SERVER_HOST + ":" + server.getPortRedirect() + "/";
    client = new URLShortenerClient(adminUrl, redirectUrl);
  }

  @AfterEach
  void stopServer() {
    if (server != null) server.shutdown();
  }

  // ─── Helper ───────────────────────────────────────────────────────────────

  private static void waitUntilOpen(String host, int port, Duration timeout) throws Exception {
    long deadline = System.nanoTime() + timeout.toNanos();
    Throwable last = null;
    while (System.nanoTime() < deadline) {
      try (Socket s = new Socket(host, port)) {
        return;
      } catch (Throwable t) {
        last = t;
        Thread.sleep(25);
      }
    }
    throw new IllegalStateException(
        "Server did not open " + host + ":" + port + " in time", last);
  }

  // ─── Happy-path tests ─────────────────────────────────────────────────────

  @Test
  void bulkShorten_allValid_allSucceed() throws IOException {
    final var response = client.bulkShorten(List.of(URL_A, URL_B, URL_C));

    assertNotNull(response);
    assertEquals(3, response.getTotal());
    assertEquals(3, response.getSucceeded());
    assertEquals(0, response.getFailed());

    for (BulkShortenItemResult r : response.getResults()) {
      assertTrue(r.isSuccess(),          "Expected success for: " + r.getOriginalUrl());
      assertNotNull(r.getShortCode(),    "ShortCode must not be null");
      assertFalse(r.getShortCode().isBlank(), "ShortCode must not be blank");
      assertNull(r.getErrorMessage(),    "No error message expected on success");
    }
  }

  @Test
  void bulkShorten_singleValidUrl_succeeds() throws IOException {
    final var response = client.bulkShorten(List.of(URL_A));

    assertEquals(1, response.getTotal());
    assertEquals(1, response.getSucceeded());
    assertEquals(0, response.getFailed());

    final BulkShortenItemResult single = response.getResults().get(0);
    assertTrue(single.isSuccess());
    assertEquals(URL_A, single.getOriginalUrl());
    assertNotNull(single.getShortCode());
  }

  @Test
  void bulkShorten_shortCodesAreAutoGenerated_notCustomAliases() throws IOException {
    final var response = client.bulkShorten(List.of(URL_A, URL_B));

    for (BulkShortenItemResult r : response.getResults()) {
      // Shortcodes must be non-blank strings generated by the server
      assertFalse(r.getShortCode().isBlank());
    }
  }

  @Test
  void bulkShorten_shortCodesAreUnique() throws IOException {
    final List<String> urls = List.of(URL_A, URL_B, URL_C);
    final var response = client.bulkShorten(urls);

    final Set<String> codes = response.getResults().stream()
        .filter(BulkShortenItemResult::isSuccess)
        .map(BulkShortenItemResult::getShortCode)
        .collect(Collectors.toSet());

    assertEquals(3, codes.size(), "Each URL must receive a distinct shortcode");
  }

  @Test
  void bulkShorten_createdLinksAreImmediatelyResolvable() throws IOException {
    final var response = client.bulkShorten(List.of(URL_A, URL_B));

    for (BulkShortenItemResult r : response.getResults()) {
      assertTrue(r.isSuccess());
      final String resolved = client.resolveShortcode(r.getShortCode());
      assertEquals(r.getOriginalUrl(), resolved,
          "Resolving " + r.getShortCode() + " should return the original URL");
    }
  }

  @Test
  void bulkShorten_sameUrlTwice_producesTwoDistinctShortCodes() throws IOException {
    // Derselbe Ziel-URL darf mehrfach eingereicht werden und erhält je einen eigenen Code.
    final var response = client.bulkShorten(List.of(URL_A, URL_A));

    assertEquals(2, response.getTotal());
    assertEquals(2, response.getSucceeded());

    final List<String> codes = response.getResults().stream()
        .map(BulkShortenItemResult::getShortCode)
        .toList();
    // Beide Codes müssen unterschiedlich sein
    assertNotEquals(codes.get(0), codes.get(1),
        "Same target URL submitted twice must still generate two distinct shortcodes");
  }

  // ─── Error-path tests ─────────────────────────────────────────────────────

  @Test
  void bulkShorten_allInvalidUrls_allFail() throws IOException {
    final var response = client.bulkShorten(
        List.of(INVALID_URL_NO_SCHEME, INVALID_URL_BAD_SCHEME, INVALID_URL_NO_TLD));

    assertEquals(3, response.getTotal());
    assertEquals(0, response.getSucceeded());
    assertEquals(3, response.getFailed());

    for (BulkShortenItemResult r : response.getResults()) {
      assertFalse(r.isSuccess());
      assertNull(r.getShortCode(),           "No shortcode expected on failure");
      assertNotNull(r.getErrorMessage(),     "Error message must be present");
      assertFalse(r.getErrorMessage().isBlank());
    }
  }

  @Test
  void bulkShorten_mixedValidAndInvalid_partialSuccess() throws IOException {
    final var response = client.bulkShorten(
        List.of(URL_A, INVALID_URL_NO_SCHEME, URL_B, INVALID_URL_BAD_SCHEME));

    assertEquals(4, response.getTotal());
    assertEquals(2, response.getSucceeded());
    assertEquals(2, response.getFailed());

    // Resultat-Reihenfolge muss der Eingabe-Reihenfolge entsprechen
    final List<BulkShortenItemResult> results = response.getResults();
    assertTrue(results.get(0).isSuccess(),  "URL_A must succeed");
    assertFalse(results.get(1).isSuccess(), "INVALID_URL_NO_SCHEME must fail");
    assertTrue(results.get(2).isSuccess(),  "URL_B must succeed");
    assertFalse(results.get(3).isSuccess(), "INVALID_URL_BAD_SCHEME must fail");
  }

  @Test
  void bulkShorten_blankEntryInList_reportsErrorForBlank() throws IOException {
    final var response = client.bulkShorten(List.of(URL_A, "   ", URL_B));

    assertEquals(3, response.getTotal());
    assertEquals(2, response.getSucceeded());
    assertEquals(1, response.getFailed());

    final BulkShortenItemResult blankResult = response.getResults().get(1);
    assertFalse(blankResult.isSuccess());
    assertNotNull(blankResult.getErrorMessage());
    assertFalse(blankResult.getErrorMessage().isBlank());
  }

  @Test
  void bulkShorten_invalidUrlHasCorrectOriginalUrlPreserved() throws IOException {
    final var response = client.bulkShorten(List.of(INVALID_URL_NO_SCHEME));

    final BulkShortenItemResult result = response.getResults().get(0);
    assertFalse(result.isSuccess());
    assertEquals(INVALID_URL_NO_SCHEME, result.getOriginalUrl(),
        "The original URL must be preserved in the error result");
  }

  @Test
  void bulkShorten_summaryCountsMatchResultsList() throws IOException {
    final var response = client.bulkShorten(
        List.of(URL_A, INVALID_URL_NO_SCHEME, URL_B));

    final long succeededInList = response.getResults().stream()
        .filter(BulkShortenItemResult::isSuccess).count();
    final long failedInList = response.getResults().stream()
        .filter(r -> !r.isSuccess()).count();

    assertEquals(response.getTotal(),     response.getResults().size(),
        "total must equal results list size");
    assertEquals(response.getSucceeded(), (int) succeededInList,
        "succeeded counter must match actual successes in list");
    assertEquals(response.getFailed(),    (int) failedInList,
        "failed counter must match actual failures in list");
  }

  // ─── Client-side validation tests ─────────────────────────────────────────

  @Test
  void bulkShorten_nullList_throwsIllegalArgumentException() {
    assertThrows(IllegalArgumentException.class,
        () -> client.bulkShorten(null),
        "null urls list must be rejected client-side");
  }

  @Test
  void bulkShorten_emptyList_throwsIllegalArgumentException() {
    assertThrows(IllegalArgumentException.class,
        () -> client.bulkShorten(List.of()),
        "empty urls list must be rejected client-side");
  }

  // ─── Volume / regression test ─────────────────────────────────────────────

  @Test
  void bulkShorten_largerBatch_allSucceed() throws IOException {
    final List<String> urls = new ArrayList<>();
    for (int i = 1; i <= 20; i++) {
      urls.add("https://example.com/page-" + i);
    }

    final var response = client.bulkShorten(urls);

    assertEquals(20, response.getTotal());
    assertEquals(20, response.getSucceeded());
    assertEquals(0,  response.getFailed());

    final Set<String> codes = response.getResults().stream()
        .map(BulkShortenItemResult::getShortCode)
        .collect(Collectors.toSet());
    assertEquals(20, codes.size(), "All 20 shortcodes must be distinct");
  }

  @Test
  void bulkShorten_resultsAreRegisteredInStore() throws IOException {
    final var response = client.bulkShorten(List.of(URL_A, URL_B));

    assertEquals(2, response.getSucceeded());

    // Die erzeugten Links müssen in der globalen Liste auftauchen
    final var allMappings = client.listAll();
    final Set<String> allCodes = allMappings.stream()
        .map(m -> m.shortCode())
        .collect(Collectors.toSet());

    for (BulkShortenItemResult r : response.getResults()) {
      assertTrue(allCodes.contains(r.getShortCode()),
          "Shortcode " + r.getShortCode() + " must appear in the store listing");
    }
  }
}
